[package]
name = "uking-relocate"
version = "0.0.0"
edition = "2021"
description = "Tool for relocating uking binaries"
publish = false

[dependencies]
anyhow = "1.0.98"
blueflame = { git = "https://github.com/Pistonite/botw-ist", rev = "4c3445f85a941358e51e88b7a55cf740374100f3", default-features = false }
clap = { version = "4.5.38", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["full"] }
elf = "0.7.4"
memchr = "2.7.4"
roead = "1.0.0"
thiserror = "2.0.12"
