[package]
name = "uking-relocate"
version = "0.0.0"
edition = "2021"
description = "Tool for relocating uking binaries"
publish = false

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["full"] }
elf = "0.7.4"
memchr = "2.7.4"
thiserror = "2.0.9"
uking-relocate-lib = { path = "./lib" }
