[package]
name = "uking-extract"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
uking-extract-common = { path = "./common" }
uking-extract-backend = { path = "./backend" }
uking-extract-frontend = { path = "./frontend" }
clap = { version = "4.5.23", features = ["derive"] }
error-stack = { version = "0.5.0", features = ["anyhow"] }
thiserror = "2.0.9"
