[package]
name = "uking-extract-backend"
version = "0.0.0"
edition = "2021"
publish = false
description = "Backend for uking-extract to read data from DWARF info"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
uking-extract-common = { path = "../common" }
derivative = "2.2.0"
elf = "0.7.4"
error-stack = "0.5.0"
gimli = "0.31.1"
num_cpus = "1.16.0"
thiserror = "2.0.12"
derive_more = { version = "2.0.1", features = ["full"] }

[features]
default = []
debug-merge = []
debug-resolve-name = [] # Debug name resolution algorithm
debug-resolve-size = []
debug-layout = [] # Debug layout optimization handling (tail padding and empty base)
debug-union-opt = [] # Debug union optimization handling
debug-create-def = []
