[package]
name = "uking-extract-frontend"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
uking-extract-common = { path = "../common"}
anyhow = "1.0.95"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde_yaml_ng = "0.10.0"
clap = { version = "4.5.23", features = ["derive"] }
error-stack = "0.5.0"
thiserror = "2.0.9"
derive_more = { version = "1.0.0", features = ["full"] }
